"""O'zgarioshlar qilindi

Revision ID: fe7f9c3a5daa
Revises: 667822e932f3
Create Date: 2026-07-11 18:08:55.563490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe7f9c3a5daa'
down_revision: Union[str, Sequence[str], None] = '667822e932f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('jobs', 'edited_at')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('edited_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('jobs', 'owner_id')
    # ### end Alembic commands ###
